#***CD to Google Drive and Import Libraries and Functions***

In [ ]:
from google.colab import drive
drive.mount('/gdrive')
#Change current working directory to gdrive
%cd /gdrive


Mounted at /gdrive
/gdrive


In [ ]:
!pip install vecstack

  Created wheel for vecstack: filename=vecstack-0.4.0-py3-none-any.whl size=19878 sha256=0c3b53e2487d5a110dea6ee337de443aa5e0e3808d3cac9bbe5799c0f1a0a17c
  Stored in directory: /root/.cache/pip/wheels/28/fe/0c/fe8e43660e3316d7ce204e59a79a72246c0ae9b6c5c79841c8
Successfully built vecstack


In [ ]:
from vecstack import stacking
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE 
from collections import Counter #for Smote, 

import warnings
warnings.filterwarnings("ignore")

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


#***Import Santander Data***

In [ ]:
trainfile = r'/gdrive/My Drive/CIS508/Assignment 1/Santander Train.csv'
trainData = pd.read_csv(trainfile)

#Read test data file
testfile = r'/gdrive/My Drive/CIS508/Assignment 1/Santander Test.csv'
testData = pd.read_csv(testfile)

trainData.head()

ID  var3  var15  ...  saldo_medio_var44_ult3       var38  TARGET
0   1     2     23  ...                     0.0   39205.170       0
1   3     2     34  ...                     0.0   49278.030       0
2   4     2     23  ...                     0.0   67333.770       0
3   8     2     37  ...                     0.0   64007.970       0
4  10     2     39  ...                     0.0  117310.979       0

[5 rows x 371 columns]

#***EDA: Preview the data***

In [ ]:
#Data Description
trainData.info()
trainData.describe()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76020 entries, 0 to 76019
Columns: 371 entries, ID to TARGET
dtypes: float64(111), int64(260)
memory usage: 215.2 MB


ID           var3  ...         var38        TARGET
count   76020.000000   76020.000000  ...  7.602000e+04  76020.000000
mean    75964.050723   -1523.199277  ...  1.172358e+05      0.039569
std     43781.947379   39033.462364  ...  1.826646e+05      0.194945
min         1.000000 -999999.000000  ...  5.163750e+03      0.000000
25%     38104.750000       2.000000  ...  6.787061e+04      0.000000
50%     76043.000000       2.000000  ...  1.064092e+05      0.000000
75%    113748.750000       2.000000  ...  1.187563e+05      0.000000
max    151838.000000     238.000000  ...  2.203474e+07      1.000000

[8 rows x 371 columns]

In [ ]:
# To check number of null values
trainData.isna().sum()

ID                         0
var3                       0
var15                      0
imp_ent_var16_ult1         0
imp_op_var39_comer_ult1    0
                          ..
saldo_medio_var44_hace3    0
saldo_medio_var44_ult1     0
saldo_medio_var44_ult3     0
var38                      0
TARGET                     0
Length: 371, dtype: int64

#***Build the Model***

##Split

In [ ]:
#Split the training data into a testing and training set for validation
X= trainData.iloc[:, :-1].values
y= trainData['TARGET']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
#Check to see if the target is balanced
y.value_counts()

0    73012
1     3008
Name: TARGET, dtype: int64

In [ ]:
#Run a preliminary decision tree
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
clf_predict=clf.predict(X_test)
print("accuracy Score (training) for Decision Tree:{0:6f}".format(clf.score(X_test,y_test)))
print("Confusion Matrix for Decision Tree")
print(confusion_matrix(y_test,clf_predict))

accuracy Score (training) for Decision Tree:0.926416
Confusion Matrix for Decision Tree
[[23114   982]
 [  864   127]]


##Oversample to Balance

In [ ]:
#We found that the target was imbalanced so we can use SMOTE, a form of oversampling, to account for that
print("___________________________________________________________________\nSMOTE\n")
print('Original dataset shape %s' % Counter(y_train))
sm = SMOTE(sampling_strategy='float', ratio=.8)
X_res, y_res = sm.fit_resample(X_train, y_train)
print('Resampled dataset shape %s' % Counter(y_res))

___________________________________________________________________
SMOTE

Original dataset shape Counter({0: 48916, 1: 2017})
Resampled dataset shape Counter({0: 48916, 1: 39132})


In [ ]:
#Run a decision tree with the "SMOTEd" set
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.33, random_state=42)
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
clf_predict=clf.predict(X_test)
print("accuracy Score (training) for Decision Tree:{0:6f}".format(clf.score(X_test,y_test)))
print("Confusion Matrix for Decision Tree")
print(confusion_matrix(y_test,clf_predict))

accuracy Score (training) for Decision Tree:0.950234
Confusion Matrix for Decision Tree
[[15300   835]
 [  611 12310]]


##Hyperparameter Tuning

In [ ]:
#Hyperparameter tuning done for decision tree
parameters={'min_samples_split' : range(10,100,10),'max_depth': range(1,20,2),'criterion':['gini','entropy']}
clf_random = RandomizedSearchCV(clf,parameters,n_iter=15)
clf_random.fit(X_train, y_train)
grid_parm=clf_random.best_params_
print(grid_parm)

#Using the parameters obtained from HyperParameterTuning in the DecisionTreeClassifier 
clf = DecisionTreeClassifier(**grid_parm)
clf.fit(X_train,y_train)
clf_predict = clf.predict(X_test)

#Obtain accuracy ,confusion matrix,classification report and AUC values for the result above.
print("accuracy Score (training) after hypertuning for Decision Tree:{0:6f}".format(clf.score(X_test,y_test)))
print("Confusion Matrix after hypertuning for Decision Tree")
print(confusion_matrix(y_test,clf_predict))
print("=== Classification Report ===")
print(classification_report(y_test,clf_predict))

#get cross-validation report
clf_cv_score = cross_val_score(clf, X_train, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(clf_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Decision Tree: ",clf_cv_score.mean())

{'min_samples_split': 10, 'max_depth': 17, 'criterion': 'entropy'}
accuracy Score (training) after hypertuning for Decision Tree:0.948513
Confusion Matrix after hypertuning for Decision Tree
[[15351   784]
 [  712 12209]]
=== Classification Report ===
              precision    recall  f1-score   support

           0       0.96      0.95      0.95     16135
           1       0.94      0.94      0.94     12921

    accuracy                           0.95     29056
   macro avg       0.95      0.95      0.95     29056
weighted avg       0.95      0.95      0.95     29056

=== All AUC Scores ===
[0.97292582 0.97148308 0.9731124  0.97096194 0.97224935 0.97160064
 0.97018386 0.97057464 0.97353561 0.97113664]


=== Mean AUC Score ===
Mean AUC Score - Decision Tree:  0.9717763997956237


##Submission File

In [ ]:
#Create the CSV to submit to Kaggle
clf_predict=clf.predict(testData)
clf_predict
result = pd.DataFrame(testData['ID'])
result['TARGET']=clf_predict
result.to_csv('/gdrive/My Drive/CIS508/Assignment 1/HypertunedDecisionTree.csv',index=None)
result.head()

ID  TARGET
0   2       0
1   5       0
2   6       0
3   7       0
4   9       0